ALTER TABLE assets
  ADD COLUMN IF NOT EXISTS width_px INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height_px INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS resolution_label TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mime_type TEXT NOT NULL DEFAULT 'application/octet-stream';
